hub/apps/content/migrations/0039_auto_20151211_1908.py
hub/apps/content/migrations/0040_auto_20151211_1918.py
hub/apps/content/migrations/0041_auto_20151211_2003.py
hub/apps/content/migrations/0042_auto_20151211_2011.py
hub/apps/content/migrations/0043_auto_20151211_2013.py
hub/apps/content/models.py
hub/apps/content/types/academic.py
hub/apps/content/types/centers.py
hub/apps/content/types/courses.py
hub/apps/content/types/presentations.py
hub/apps/content/types/publications.py
hub/apps/submit/forms.py
hub/apps/submit/views.py
hub/static/js/base.js
hub/static/js/submit-form.js
hub/static/vendor/jquery-django-inline-form/django-inline-form.js
hub/templates/forms/base.html
hub/templates/forms/checkbox.html
hub/templates/forms/select_multiple.html
hub/templates/submit/form.html
hub/templates/submit/includes/author_detail_form.html
hub/templates/submit/includes/authors.html
hub/templates/submit/includes/files.html
hub/templates/submit/includes/files_detail_form.html
hub/templates/submit/includes/images.html
hub/templates/submit/includes/images_detail_form.html
hub/tests/test_submit.py

A number of fixes to submission forms;

Form field ordering

---

docs/heroku.md
hub/apps/metadata/migrations/0010_sustainabilitytopic_css_class.py
hub/apps/metadata/migrations/0011_topic_hex_to_css.py
hub/apps/metadata/migrations/0012_auto_20160106_0323.py
hub/apps/metadata/models.py
hub/static/scss/_aashe_unify.scss
hub/static/scss/base.scss
hub/templates/browse/home.html

Updates to use the aashe brand colors

aashe theming

---

hub/templates/submit/index.html

Converted guidelines to block content with id 'submission_guidelines'.

Issue #166: Fix typo on submit a resource page and make editable

---

hub/apps/submit/views.py
hub/templates/submit/form.html

Breadcrumbs more complicated than I thought, might as well merge this in now.

Issue #171

---

hub/apps/browse/views.py
hub/templates/base.html
hub/templates/browse/details/base.html
hub/templates/browse/results/base.html
hub/templates/registration/logged_out.html
hub/templates/registration/login.html
hub/templates/submit/base.html
hub/templates/submit/form.html

Issue #62: Breadcrumbs

---

hub/apps/content/admin.py
hub/apps/content/migrations/0060_contenttype_date_created.py
hub/apps/content/migrations/0061_migrate_created_dates.py
hub/apps/content/migrations/0062_auto_20160502_1721.py
hub/apps/content/models.py
hub/apps/content/tests/test_admin_urls.py
hub/apps/content/types/academic.py
hub/apps/content/types/centers.py
hub/apps/content/types/presentations.py
hub/apps/content/types/publications.py
hub/templates/browse/details/academicprogram.html
hub/templates/browse/details/base.html
hub/templates/browse/details/centerandinstitute.html
hub/templates/browse/details/presentation.html
hub/templates/browse/details/publication.html
hub/tests/test_required_fields.py

Added global date_created field and updated admin;

---

hub/apps/browse/filter.py
hub/apps/browse/filterset.py
hub/apps/content/types/academic.py
hub/apps/content/types/casestudies.py
hub/apps/content/types/centers.py
hub/apps/content/types/courses.py
hub/apps/content/types/outreach.py
hub/apps/content/types/photographs.py
hub/apps/content/types/presentations.py
hub/apps/content/types/publications.py
hub/apps/content/types/tools.py
hub/apps/content/types/videos.py
hub/tests/base.py
hub/tests/test_filter.py

This also adds the concept of custom filter sets for all content types.
In the future this could be used to limit choice selections for shared
filters;

Added filter for date created; Fixes #284;

---

hub/apps/content/migrations/0063_auto_20160513_1349.py
hub/apps/content/models.py
hub/apps/submit/forms.py
hub/templates/browse/details/base.html
hub/templates/browse/results/includes/filter.html

Styling issue: button and icon color changed to match aashe green.
Admin issue: restored ability to edit resource slug.

Issues 92 and 254

---

hub/apps/access/__init__.py
hub/apps/access/admin.py
hub/apps/access/apps.py
hub/apps/access/models.py
hub/permissions.py
hub/settings/base.py
hub/tests/test_browse.py

Temp access

---

.gitignore
hub/apps/browse/filter.py
hub/apps/browse/filterset.py
hub/apps/content/admin.py
hub/templates/browse/details/base.html
hub/tests/test_filter.py

Added filter for academic discipline and modified related tests to include this filter field.

Issue #237: Add Discipline filter

---

hub/templates/search/indexes/content/base.txt
hub/tests/test_search.py

Added author objects' names to search index base template.

Issue #223: Add author names to search index

---

hub/apps/browse/filterset.py
hub/apps/content/migrations/0065_migrate_case_study_published_dates.py
hub/apps/content/models.py
hub/apps/content/types/casestudies.py
hub/apps/submit/views.py
hub/templates/browse/details/base.html
hub/tests/test_content.py
hub/tests/test_submit.py

#318: Copying published date into date_created field. Added migration to populate for all existing case studies.
#92: Cosmetic tweak for "Request a Change" button.
#328: Reorder filter fields

Issues #92, #318, #328

---

hub/apps/browse/views.py
hub/apps/content/migrations/0079_auto_20160801_1850.py
hub/apps/metadata/migrations/0021_sustainabilitytopic_scpd_rss_feed.py
hub/apps/metadata/models.py
hub/static/scss/base.scss
hub/templates/browse/results/includes/partners.html
hub/templates/browse/results/topic.html
hub/tests/test_caching.py

Add syndication of SCPD profiles as "Partners" tab added to Sustainability Topic browse pages.

Partners Tab

---

hub/apps/content/management/commands/truncate_db.py
hub/static/scss/base.scss
hub/templates/browse/results/base.html
hub/templates/browse/results/includes/item.html

Scott image features

---

hub/templates/browse/results/includes/item.html

Add markdown to search results

---

hub/apps/content/admin.py
requirements.txt

Added thumbnailing support to the admin;

Bug fix for #420 and #454;

---

hub/apps/browse/templatetags/browse_tags.py
hub/templates/browse/results/includes/item.html

Changed the label of the label that is populated in the tooltip in browse_tags.py according to Julian's request. Updated hub/templates/browse/results/includes/item.html to pass icon_only as true.

Membership required,  issue #418

---

hub/apps/browse/filter.py
hub/apps/browse/filterset.py
hub/templates/browse/details/base.html

Added institutional office to resource detail (labeled as Office or Department), with hyperlink. Added filterable field to all list pages, labeled Office or Department.

Institution offices, Issue #207

---

hub/templates/submit/includes/authors.html

Change Conference Presentation resource submission author form to check if the content type is 'Conference Presentation.' If yes, change 'Author' to 'Presenter.'
Resolves: #191

Change presentation resource submission to say Add Presenter; Issue #191

---

hub/static/js/base.js
hub/static/js/toolkit.js
hub/static/scss/base.scss
hub/templates/browse/results/base.html
hub/templates/browse/results/includes/toolkit.html

Fix indentation issues on Toolkit Featured Resources.
Added jquery logic to simplify view. Added bootstrap col classes to separate elements.
Resolves: #265

Featured resource indentation; Issue #265

---

requirements.txt

Update to iss with fixed typo.

Update iss version

---

hub/apps/content/admin.py

Publish the resource submitter name and email in the Admin.
Remove the cryptic 'submitted_by' id.
Resolves: #222

Submitter name; Issue #222

---

hub/apps/browse/templatetags/browse_tags.py
hub/static/js/details.js
hub/templates/browse/details/base.html

Embed video resources when it is possible.
Youtube and Vimeo formats are supported.

Embed videos

---

hub/apps/submit/views.py

Fix the MultipleObjectsReturned error on submission pages

Fix MultipleObjectsReturned error

---

docs/search.md
hub/apps/browse/filter.py
hub/settings/base.py
hub/settings/server.py
hub/templates/search/indexes/content/base.txt

Merge Brian's search branch into master to implement his changes.

Search tuning

---

hub/apps/browse/templatetags/browse_tags.py

Find a better way to identify the video id in youtube urls.

Support youtube links more dynamically

---

hub/apps/browse/filter.py

Push search ordering to ordering filter, and remove the workaround.

Search filter bug

---

hub/apps/content/management/commands/update_academic_programs.py

Execute management command to update all academic programs to 'open' permission.

Update all academic programs to the correct permission

---

hub/tests/base.py
hub/tests/test_browse.py
hub/tests/test_caching.py
hub/tests/test_filter.py
hub/tests/test_search.py
requirements.txt

Bring the tests to a state of passing.

Test suite

---

hub/apps/submit/forms.py
hub/apps/submit/utils.py
hub/settings/base.py
hub/templates/submit/resource_submitted_email.txt

Send email to submitter upon resource submission.

Submission email

---

hub/apps/content/admin.py

Add 'date posted' to case studies.

Date posted

---

hub/apps/browse/filter.py

Get all organizations with selected type. Then filter existing queryset based on organizations present in the organization queryset.

Filter qs on qs of orgs with selected type

---

hub/apps/content/types/green_funds.py
hub/templates/search/indexes/content/greenfund_text.txt

Allow greenfunds to be indexed.

Add greenfund index text file.

---

hub/apps/browse/filter.py
hub/apps/content/models.py
hub/templates/base.html
hub/templates/browse/details/base.html

Clear some of the issues in spring sprint.

Spring sprint

---

hub/apps/browse/views.py
hub/apps/content/admin.py
hub/templates/base.html

some additional changes for this week.

Spring spint 2

---

hub/apps/content/management/commands/get_all_file_urls.py
hub/apps/content/management/commands/rename_files.py
hub/settings/base.py

Make sure all future file uploads do not have plus nor space in their name. Add scripts to find all the files with special characters in their name, as well as a script to correct those files.

File encoding
